---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker
  settings:
    dryrun: true
    dockerfile: Dockerfile 
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    username:
      from_secret: docker_username
    purge: true
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-amd64
    purge: true
  when:
    exclude:
    - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

...
